### ISSUE TITLE
Negative scale on transforms causes collider to stop detecting collisions.

### ISSUE THREAD

**Issue by Sandvoxel** [Jondolf/avian#287]
I've encountered an issue in the Bevy XPBD 3D plugin where applying a negative scale to an entity's transform seems to prevent its collider from interacting as expected. Specifically, when a negative scale is applied to an entity, the collider associated with it appears to stop detecting collisions or behaving correctly in the physics simulation.

Steps to Reproduce:
1. Create an entity with a collider component.
2. Apply a negative scale to the entity's transform (e.g., `Transform::from_scale(Vec3::new(-1.0, 1.0, 1.0))`).
3. Observe the behavior of the collider in the physics simulation.

Expected Behavior:
The collider should continue to function normally, detecting collisions and responding to physics interactions, regardless of the entity's scale sign.

Actual Behavior:
The collider ceases to detect collisions or respond correctly once a negative scale is applied.

I am unsure if this is an intended behavior or a bug. Any insights or suggestions on how to address this issue would be greatly appreciated.

**Comment by Jondolf** [comment]
This should be mostly fixed as of #472, and collisions should now work with negative scales; feel free to reopen this or open a new issue if that's not the case (it can vary per shape!)

Note that there may still be some shapes that don't get mirrored correctly at the moment, and there's an issue where negative scale might be propagated wrong for collider hierarchies. See #471.
