### ISSUE TITLE
Rigidbodies never sleep

### ISSUE THREAD

**Issue by Klohger** [Jondolf/avian#357]
Whenever a rigidbody begins sleeping, it immediately gets woken up. I've tried debugging, and I'm guessing the problem is that the change of external forces needs to be checked if they're above the sleeping threshold. I'm not exactly an expert when it comes to physics engines, so I cannot exactly say where the fault lies.

**Comment by Jondolf** [comment]
I think this issue might've been introduced by [automatically inserted `apply_deferred` systems](https://bevyengine.org/news/bevy-0-13/#automatically-insert-apply-deferred-systems) added in Bevy 0.13. The sleeping logic was previously relying on some rather questionable and precise scheduling, and there might be some new `apply_deferred` systems that break it. I'll try to look into this more to verify.

Either way, I think the sleeping logic should be partially rewritten as it's currently not very robust or optimal. I have plans to experiment with ["simulation islands"](https://box2d.org/posts/2023/10/simulation-islands/), which would both increase parallelization and help handle sleeping properly.

**Comment by Jondolf** [comment]
This was partially fixed by the solver rework (#385) in Avian 0.1. Bodies should now fall asleep again, but only if they're not interacting with other dynamic bodies. I'll close this, and open a separate issue for simulation islands soon
