### ISSUE TITLE
Rework mass properties

### ISSUE THREAD

**Issue by janhohenheim** [Jondolf/avian#443]
[Context](https://discord.com/channels/691052431525675048/1124043933886976171/1262497766429692005)
Quoting @Jondolf:
> Mass properties are one of the messiest user-facing parts, and we really need to rework them a lot

One thing that needs to be more accessible is getting the density of a collider / rigid body.

**Comment by Jondolf** [comment]
I made a write-up laying out a lot of the current problems, along with a proposal for overhauling mass properties: #499
