### ISSUE TITLE
Fix one way example

### ISSUE THREAD

**Issue by adsick** [Jondolf/avian#456]
There is a minor problem in the `crates/avian2d/examples/one_way_platform_2d.rs` example - If you drop all the way down you can not climb back up because the lower platform will pass you through.

https://github.com/user-attachments/assets/15e5af2b-f711-460d-81c0-129b4ff22164

**Comment by datael** [comment]
This no longer occurs on main.

I ran a bisect and this appears to be fixed as-of 4d082a79fd30078e5b536ae23656f690091ae285 (PR: https://github.com/Jondolf/avian/pull/457: switching to FixedPostUpdate)
It's a 100% repro until that commit.

**Comment by Jondolf** [comment]
Closing as fixed in that case; feel free to reopen or make a new issue if this is still reproducable for you
