### ISSUE TITLE
Incorrect CenterOfMass for ColliderConstructorHierarchy with scale up transform

### ISSUE THREAD

**Issue by MikMikus** [Jondolf/avian#479]
When i load gltf model with scale up transform and use `ColliderConstructorHierarchy`, automatically added  `CenterOfMass` for whole entity is posited outside model.

See [`collider_constructors`](https://github.com/Jondolf/avian/blob/main/crates/avian3d/examples/collider_constructors.rs) example and change `.with_scale(Vec3::splat(2.0))` to eg. `.with_scale(Vec3::splat(10.0))`.

![obraz](https://github.com/user-attachments/assets/91f9a2b0-8c56-470d-8b03-22f15b31781f)

Update:
I'm not sure, but looks like [this](https://github.com/Jondolf/avian/blob/e2a16959ea7bc8c0ba37b7c757fcfa8858ba6392/src/collision/collider/backend.rs#L717) doesn't work as expected:
```rust
if !collider.is_added() {
    mass_properties -=
        collider_mass_properties.transformed_by(&previous_collider_transform);
}
```

**Comment by Jondolf** [comment]
This seems to have been fixed by #574.
