### ISSUE TITLE
No error if entity has transform but not global transform.

### ISSUE THREAD

**Issue by coolcatcoder** [Jondolf/avian#484]
I created a physics entity and simply forgot to use transform bundle instead of transform. Position and Transform do not sync. It took me almost an hour to work out I had just forgotten that global transform. Perhaps a warning would be appreciated?

**Comment by dmyyy** [comment]
GlobalTransform will be automatically added when you add a Transform with required components in 0.15.

**Comment by coolcatcoder** [comment]
Nice!
