### ISSUE TITLE
Is avian2d broken with latest bevy git source?

### ISSUE THREAD

**Issue by fernanlukban** [Jondolf/avian#521]
I currently changed my config to use bevy using git as the source, and I am trying to compile my project. Previously, it had compiled fine, but now I am getting 

```
13  |     q_colliding_with_mouse: Query<&mut CollidingEntities, With<MouseInput>>,
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ invalid `Component`
    |
    = help: the trait `bevy::prelude::Component` is not implemented for `CollidingEntities`, which is required by `&mut CollidingEntities: QueryData`
    = note: consider annotating `CollidingEntities` with `#[derive(Component)]`
    = help: the following other types implement trait `bevy::prelude::Component`:
              AccessibilityNode
              AnimationPlayer
              AnimationTarget
              AnimationTransitions
              AppExit
              AssetEvent<A>
              AssetLoadFailedEvent<A>
              AudioSink
            and 296 others
    = note: required for `&mut CollidingEntities` to implement `QueryData`
```

Does the latest bevy have a breaking change and should I create a PR to fix this? I'm looking at some code and it might look like I need to implement QueryData for this? Though not sure why it was working with the release and not the latest version of bevy.

**Comment by Jondolf** [comment]
Avian 0.1 and Avian's main branch use Bevy 0.14. You cannot use Bevy's main branch without forking Avian to use it as well, since threre are breaking changes, and Rust tends to think the types between 0.14 and main are different and incompatible.

**Comment by fernanlukban** [comment]
Sounds good, looks like I will just fork it and try to fix it since there are some custom icon things that are broken in the current release but not the main branch.

**Comment by Jondolf** [comment]
Cool, I'll close this issue then. If you have any follow-up questions though, feel free to ask here or on Discord :)
