### ISSUE TITLE
Unable to get custom type shaped colliders

### ISSUE THREAD

**Issue by tompuric** [Jondolf/avian#595]
Hi,

I would like to identify the dimensions of my collider.

I am able to currently do so for a ball like so

```rs
if let Some(polygon) = collider.shape().as_ball() {
  return (polygon.radius * 2.0, polygon.radius * 2.0);
}
```

But I am unable to perform this same action for an Ellipse.
I can see in the gizmos that you achieve this internally via

```rs
if let Some(ellipse) = collider.shape_scaled().as_shape::<EllipseWrapper>() {
  ...
}
```

But `EllipseWrapper`, and other parry/primitives are unavailable.
Is this intentional? Is there anyway I can get this data? Thanks.

**Workaround**
Use a non-custom type shape

**Comment by zxsa89675** [comment]
Hello, we tried to solve the issue.

This is what we did:

1. Expose EllipseWrapper and RegularPolygonWrapper in the public API.
2. Add a new method to Collider to get dimensions for various shape types, including custom shapes.
3. Implement the new method for different shape types.

You can review changes in this commit: https://github.com/zxsa89675/Jondolf-avian-595/commit/1291dec3da23d2b54537b31f1bab900c98bb5eb5.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Jondolf** [comment]
Hah, I guess we're getting AI responses now... That account should now be blocked :P

Those wrapper types were originally created just to allow creating colliders from Bevy's shapes that are not supported by Parry, and I didn't consider that people might want to access them at runtime too. It's a valid use case though, so I opened #596 to make them public :)

**Comment by tompuric** [comment]
Thanks @Jondolf , this works for me now ❤️
