### ISSUE TITLE
Collider wireframes

### ISSUE THREAD

**Issue by Dashurai** [Jondolf/avian#603]
Are there plans to add an equivalent to `RapierDebugRenderPlugin` ? Especially wireframes, as meshes and materials do not guarantee to exactly match the collider's shape and state (e.g. is a force applied) while also adding boilerplate.
If not, what are your solutions to visualize colliders that do not require an external tool ?

Thanks in advance.

**Comment by Jondolf** [comment]
This already exists, see [`PhysicsDebugPlugin`](https://docs.rs/avian3d/latest/avian3d/debug_render/struct.PhysicsDebugPlugin.html).
